apiVersion: v1
kind: Service
metadata:
  name: cv-onepage
  namespace: default
spec:
  type: NodePort
  selector:
    app: cv-onepage
  ports:
    - protocol: TCP
      port: 81        # Port interne du container (celui que tu as défini dans Dockerfile)
      targetPort: 81
      nodePort: 8585  # Port externe accessible depuis ta machine physique
